### PR TITLE
[HotFix] Ensure cryp4gh keys are loaded on startup.

### LINKED ISSUE #1597: [Ingest] don't fail startup if no c4gh key is configured
## Describe the bug
If the `c4gh.privateKeys` list is empty, Ingest will happily start anyway.

## Expected behavior
- [ ] Ingest should fail hard and loud if no crypt4gh key has been configured
- [ ] Tests verifying the fix are added

## Additional context
Affected versions >= v0.3.180

## Estimation of size
small

## Estimation of priority
high

### LINKED ISSUE #1662: Applications start without configured c4gh keys
## Describe the bug

Both ingest and verify will happily start even if no crypt4gh keys have been configured.
No errors will be reported until the apps try to decrypt a file during the work process.

## Steps to reproduce

Remove the `c4gh.privateKeys` block from the config file and run `make integrationtest-sda-s3-run`

## Expected behavior
- [ ] Ingest and verify should fail fast and hard if no crypt4gh keys are configured.
- [ ] Tests verifying the fix are added

## Estimation of size
small

## Estimation of priority
high

### PR DESCRIPTION
**Pull request by jbygdell**
## Related issue(s) and PR(s)
This PR closes #1597  
This PR closes #1662.

## Description
This PR fixes a bug in the code where `Ingest` and `Verify` would happily start even when no crypt4gh keys have been configured.

## How to test
Remove the `c4gh.privateKeys` block from the config file and run `make sda-s3-up`

## Extra info

Chart tests will fail since the charts are not updated to handle multiple keys yet. (WIP to be completed once this is merged.)

### CODE REVIEW

File: sda/cmd/verify/verify.go [hunk 1]
```diff
@@ -41,8 +41,8 @@ func main() {
 		log.Fatal(err)
 	}
 	archiveKeyList, err := config.GetC4GHprivateKeys()
-	if err != nil {
-		log.Fatal(err)
+	if err != nil || len(archiveKeyList) == 0 {
+		log.Fatal("no C4GH private keys configured")
```
Comment (pontus) [inline sda/cmd/verify/verify.go:45]: Would be nice to provide error if this is because of one?

File: sda/cmd/ingest/ingest.go [hunk 2]
```diff
@@ -75,10 +76,9 @@ func main() {
 		panic(err)
 	}
 	app.ArchiveKeyList, err = config.GetC4GHprivateKeys()
-	if err != nil {
-		log.Error(err)
+	if err != nil || len(app.ArchiveKeyList) == 0 {
 		sigc <- syscall.SIGINT
-		panic(err)
+		panic(errors.New("no C4GH private keys configured"))
```
Comment (pontus) [inline sda/cmd/ingest/ingest.go:81]: If we're failing because of an error, it's helpful showing what.

**Review by pontus — APPROVED** [review]

File: sda/cmd/verify/verify.go (hunk 1 above)
Comment (nanjiangshu) [reply sda/cmd/verify/verify.go:45]: I agree. Maybe something like this:

```suggestion
if err != nil {
	log.Fatalf("encountered an error: %v", err)
}
if len(archiveKeyList) == 0 {
	log.Fatal("no C4GH private keys configured")
}
```

**Review by nanjiangshu — COMMENTED** [review]
Looks good to me except for the comment about the error message handling. In addition, the deployment of helm chart (ingest and verify services) is failing because of missing c4gh keys.

File: sda/cmd/verify/verify.go (hunk 1 above)
Comment (jbygdell) [reply sda/cmd/verify/verify.go:45]: The errors are printed in the`GetC4GHprivateKeys` function

File: sda/cmd/ingest/ingest.go (hunk 2 above)
Comment (jbygdell) [reply sda/cmd/ingest/ingest.go:81]: The errors are printed in the`GetC4GHprivateKeys` function

Comment (pontus) [reply sda/cmd/ingest/ingest.go:81]: It's seldom I feel there's too much information about why something fails and I would prefer not to rely on some other part of code to do things that aren't obviously part of the contract.

But if you feel it's enough it's approved.

**Comment by jbygdell** [comment]
> In addition, the deployment of helm chart (ingest and verify services) is failing because of missing c4gh keys.

I know, it is in the PR description..
But it is a catch 22 thing, Merging this PR will make fixing the charts much easier since these two services will fail if not configured properly.

**Review by nanjiangshu — APPROVED** [review]

File: sda/cmd/ingest/ingest_test.go [hunk 3]
```diff
@@ -723,3 +735,9 @@ func (ts *TestSuite) TestIngestFile_missingFile() {
 
 	assert.Equal(ts.T(), "ack", ts.ingest.ingestFile(corrID, message))
 }
+func (ts *TestSuite) TestDetectMisingC4GHKeys() {
+	viper.Set("c4gh.privateKeys", "")
+	privateKeys, err := config.GetC4GHprivateKeys()
+	assert.NoError(ts.T(), err)
+	assert.Equal(ts.T(), 0, len(privateKeys))
+}
```
Comment (aaperis) [inline sda/cmd/ingest/ingest_test.go:743]: What does this part check? Does it check that `config.GetC4GHprivateKeys` translates an empty string to an empty array?

Comment (jbygdell) [reply sda/cmd/ingest/ingest_test.go:743]: Sanity check for the current functionality.
It should be possible to have the function to return an error if the marshaled struct is empty. It was a bit to time consuming to get it to work for this PR.
