### PR TITLE
fix blank page on failed ega login

### LINKED ISSUE #1416: [Auth] EGA login doesn't work when an error occurs
## Describe the bug

Authenticating with the EGA option results in a blank page.

## Steps to reproduce

make build-all
make sda-s3-up

Authenticate with wrong user/password and the response is a blank page. This should at the least show a page with an authentication error i.e. `incorrect username or password supplied`

## Expected behavior
- [ ] Properly report to the user that something went wrong
  - [ ] wrong username and/or password (401)
  - [ ] badly configured auth service i.e responses of 404, 503, 502 and so on from the backend
- [ ] Tests verifying the fix are added

## Estimation of size
small/medium/big

## Estimation of priority
low/medium/high

### PR DESCRIPTION
**Pull request by MalinAhlberg**
## Related issue(s) and PR(s)
This PR closes #1416 .

## Description
This PR
- fixes the bug that caused the blank page when logging in with bad credentials from the user. _Provided credentials are not valid_ is shown
- fixes the bug that caused the blank page when auth service is badly configured (`auth_cega_id` or `auth_cega_secret` is wrong). _Problems connecting to EGA authenticaton server_ is shown
- fixes the bug that lead to _This page isn't worknig_ when `cega-nss` is down. _EGA authentication server could not be contacted_ is shown.
- fixes some unrelated typos in the README

## How to test
- [ ] `make sda-s3-up`
- [ ] navigate to `localhost:8888`, choose the EGA login, and try to log in with a bad username/password
- [ ] verify that the page is not blank, but contains an error message and a new login form
- [ ] Stop `cega-nss` and verify that the page does not break when trying to log in
- [ ] Change `AUTH_CEGA_SECRET` in `.github/integration/sda-s3-integration.yml` and verify that the page does not turn blank or break when trying to log in.
- [ ] Please test anything else you might come up with

**Additional notes**
No tests are added, manual testing of the webpage will still be the standard.

### CODE REVIEW

**Review by aaperis — APPROVED** [review]
Works great! :smile:

**Comment by MalinAhlberg** [comment]
> Works great! 😄

Thanks for the quick review! I realized there were some more problems though, they are now fixed in bd52543  and 45654b4.

File: sda/cmd/auth/main.go [hunk 1]
```diff
@@ -118,13 +118,16 @@ func (auth AuthHandler) postEGA(ctx iris.Context) {
 
 	res, err := authenticateWithCEGA(auth.Config.Cega, username)
 
+	var statusCode int
 	if err != nil {
 		log.Error(err)
+		statusCode = 404
+	} else {
+		statusCode = res.StatusCode
+		defer res.Body.Close()
```
Comment (jbygdell) [inline sda/cmd/auth/main.go:127]:
```suggestion
	if err != nil {
		log.Errorf("cega connection error: %v",err)
		res = &http.Response{
			Body: io.NopCloser(nil),
			StatusCode: http.StatusInternalServerError,
		}
```

This also means that the 404 case below needs to be replaced with:
`case 500,502,503:` so that we cover all bases when the NSS server misbehaves.

File: sda/cmd/auth/main.go [hunk 2]
```diff
@@ -118,13 +118,16 @@ func (auth AuthHandler) postEGA(ctx iris.Context) {
...
 	}
 
-	defer res.Body.Close()
-
-	switch res.StatusCode {
+	switch statusCode {
```
Comment (jbygdell) [inline sda/cmd/auth/main.go:130]:
```suggestion
	defer res.Body.Close()

	switch res.StatusCode {
```

**Review by jbygdell — CHANGES_REQUESTED** [review]

**Comment by MalinAhlberg** [comment]
I did the refactoring suggested by @jbygdell in a7999d3 and added some extra checks b456ef0. The last commit is another small refactoring, everything else is just rebasing.

**Review by jbygdell — APPROVED** [review]

**Review by nanjiangshu — APPROVED** [review]
Looks good. Good job!
